-- Seed MCP servers data
-- Source: aitmpl.com/mcps (69 MCPs)
-- Generated: 2026-03-16

INSERT INTO public.mcp_servers (name, slug, description, deploy_type, category, usage_count, verified, featured, published) VALUES
-- Featured (2000+ downloads)
('Context7', 'context7', 'Context7 MCP pulls up-to-date, version-specific documentation and code examples straight from the source — and places them directly into your prompt.', 'remote', 'development', 11788, true, true, true),
('Memory Integration', 'memory-integration', 'Persistent memory and context management for Claude Code sessions. Store and recall information across conversations and projects.', 'remote', 'automation', 5302, true, true, true),
('Playwright MCP Server', 'playwright-mcp-server', 'A Model Context Protocol server that provides browser automation capabilities using Playwright. Enables LLMs to interact with web pages, take screenshots, generate test code and execute JavaScript in a real browser environment.', 'local', 'automation', 4294, true, true, true),
('Web Fetch', 'web-fetch', 'Web content fetching and data extraction capabilities. Access external APIs, scrape web content, and integrate external data sources.', 'remote', 'development', 2976, true, true, true),
('PostgreSQL Integration', 'postgresql-integration', 'Connect to PostgreSQL databases for advanced data operations, complex queries, and enterprise database management.', 'remote', 'data', 2731, true, true, true),
('Supabase', 'supabase', 'Connect your Claude Code to Supabase using MCP.', 'remote', 'data', 2713, true, true, true),
('Chrome DevTools', 'chrome-devtools', 'A Model Context Protocol server for interacting with Chrome DevTools, enabling browser automation, debugging, and performance analysis.', 'remote', 'development', 2638, true, true, true),
('GitHub Integration', 'github-integration', 'Direct GitHub API integration for repository management, issue tracking, pull requests, and collaborative development workflows.', 'remote', 'automation', 2537, true, true, true),
('Filesystem Access', 'filesystem-access', 'Secure filesystem access for Claude Code with configurable directory permissions and file operations.', 'local', 'storage', 2059, true, true, true),

-- Verified (1000+ downloads)
('Browser Use MCP Server', 'browser-use-mcp-server', 'An MCP server that enables AI agents to control web browsers using browser-use.', 'local', 'automation', 1531, true, false, true),
('Playwright MCP', 'playwright-mcp', 'A Model Context Protocol server that provides browser automation capabilities using Playwright.', 'local', 'automation', 1311, true, false, true),
('Deepgraph Next.js', 'deepgraph-nextjs', 'Deep code analysis and visualization for Next.js projects. Understand component relationships, dependencies, and architecture.', 'remote', 'development', 1031, true, false, true),

-- Standard MCPs
('MySQL Integration', 'mysql-integration', 'Connect to MySQL databases for direct data access, queries, and database management within Claude Code.', 'remote', 'data', 982, false, false, true),
('Markitdown', 'markitdown', 'Convert various file formats (PDF, Word, Excel, images, audio) to Markdown.', 'remote', 'development', 895, false, false, true),
('Figma Dev Mode', 'figma-dev-mode', 'The Dev Mode MCP server brings Figma directly into your workflow by providing important design information for development.', 'remote', 'design', 842, false, false, true),
('Deepgraph React', 'deepgraph-react', 'Analyze React component hierarchies, state flows, and dependencies. Visualize your React application architecture.', 'remote', 'development', 841, false, false, true),
('iOS Simulator MCP', 'ios-simulator-mcp', 'Control iOS Simulator directly from Claude Code. Launch apps, take screenshots, manage device states.', 'remote', 'development', 730, false, false, true),
('Deepgraph TypeScript', 'deepgraph-typescript', 'Comprehensive TypeScript code analysis with type mapping, interface relationships, and module dependencies.', 'remote', 'development', 686, false, false, true),
('Serena', 'serena', 'Semantic code retrieval and editing tools for coding agents.', 'remote', 'development', 643, false, false, true),
('MCP Server Playwright', 'mcp-server-playwright', 'A Model Context Protocol server that provides browser automation capabilities using Playwright.', 'local', 'automation', 607, false, false, true),
('BrowserMCP', 'browsermcp', 'With Browser MCP, you can use MCP to automate your browser so that AI applications can navigate the web.', 'local', 'automation', 595, false, false, true),
('Notion', 'notion', 'Official MCP server for Notion API.', 'remote', 'productivity', 418, false, false, true),
('Deepgraph Vue', 'deepgraph-vue', 'Analyze Vue.js applications including component composition, reactive data flow, and template-script relationships.', 'remote', 'development', 377, false, false, true),
('HuggingFace', 'huggingface', 'Access Hugging Face models, datasets, Spaces, papers, collections via MCP.', 'remote', 'ai', 333, false, false, true),
('Linear', 'linear', 'MCP server for integrating Linear project management and issue tracking.', 'remote', 'productivity', 323, false, false, true),
('Deepgraph Python', 'deepgraph-python', 'Analyze Python codebases with module dependency graphs, class hierarchies, and function call analysis.', 'remote', 'development', 316, false, false, true),
('Bright Data', 'bright-data', 'Bright Data MCP server that allows LLMs to access, discover, and extract web data.', 'remote', 'data', 315, false, false, true),
('Slack Integration', 'slack-integration', 'MCP server for Slack workspace integration, enabling channel management, messaging, and team collaboration.', 'remote', 'communication', 296, false, false, true),
('Deepresearch', 'deepresearch', 'Deep research capabilities for comprehensive topic investigation and analysis.', 'remote', 'ai', 285, false, false, true),
('Sqlite Integration', 'sqlite-integration', 'A lightweight SQLite integration for local database operations and data management.', 'local', 'data', 284, false, false, true),
('Stagehand', 'stagehand', 'An AI web browsing framework that combines computer vision and DOM manipulation for reliable browser automation.', 'local', 'automation', 277, false, false, true),
('Railway', 'railway', 'MCP server for Railway deployment platform integration.', 'remote', 'automation', 265, false, false, true),
('Deepgraph Angular', 'deepgraph-angular', 'Analyze Angular applications with dependency injection mapping, module relationships, and component hierarchies.', 'remote', 'development', 260, false, false, true),
('Audioscribe', 'audioscribe', 'Audio transcription and analysis capabilities for processing audio content.', 'remote', 'ai', 253, false, false, true),
('Firecrawl', 'firecrawl', 'Turn any website into LLM-ready data with web scraping, crawling, and extraction.', 'remote', 'data', 251, false, false, true),

-- Lower usage MCPs
('PostgreSQL Documentation', 'postgresql-documentation', 'PostgreSQL documentation and skills for writing better Postgres code.', 'remote', 'data', 239, false, false, true),
('Grafana', 'grafana', 'A Model Context Protocol server for interacting with Grafana dashboards and monitoring.', 'remote', 'development', 236, false, false, true),
('Sentry', 'sentry', 'Model Context Protocol for interacting with Sentry, focused on human-in-the-loop coding agents and developer workflows.', 'remote', 'development', 194, false, false, true),
('ElevenLabs', 'elevenlabs', 'Official ElevenLabs MCP for text-to-speech, voice cloning, audio processing, and transcription.', 'remote', 'ai', 190, false, false, true),
('ImageSorcery', 'imagesorcery', 'An MCP server providing tools for image processing operations.', 'remote', 'design', 183, false, false, true),
('Neon', 'neon', 'MCP server for interacting with Neon Management API and databases.', 'remote', 'data', 175, false, false, true),
('Atlassian Bitbucket', 'atlassian-bitbucket', 'A Model Context Protocol server for Atlassian Bitbucket Cloud. Enables AI systems to interact with Bitbucket repositories and workspaces.', 'remote', 'automation', 169, false, false, true),
('Atlassian Jira', 'atlassian-jira', 'A Model Context Protocol server for Atlassian Jira. Enables AI systems to interact with Jira projects, issues and workflows.', 'remote', 'productivity', 166, false, false, true),
('Atlassian Confluence', 'atlassian-confluence', 'A Model Context Protocol server for Atlassian Confluence. Enables AI systems to interact with Confluence pages and spaces.', 'remote', 'productivity', 152, false, false, true),
('Deepgraph Svelte', 'deepgraph-svelte', 'Analyze Svelte applications with component flow, reactive declarations, and store patterns.', 'remote', 'development', 148, false, false, true),
('PocketBase', 'pocketbase', 'MCP server for PocketBase backend integration and management.', 'remote', 'data', 141, false, false, true),
('Docling', 'docling', 'Document processing and conversion capabilities for various file formats.', 'remote', 'development', 137, false, false, true),
('Tavily', 'tavily', 'AI-powered search and research capabilities via Tavily API.', 'remote', 'ai', 137, false, false, true),
('Vercel', 'vercel', 'MCP server for Vercel platform integration and deployment management.', 'remote', 'automation', 130, false, false, true),
('Cloudflare', 'cloudflare', 'MCP server for Cloudflare platform integration and management.', 'remote', 'automation', 127, false, false, true),
('Google Drive', 'google-drive', 'MCP server for Google Drive file management and collaboration.', 'remote', 'storage', 122, false, false, true),
('Mongo Integration', 'mongo-integration', 'Connect to MongoDB databases for document-based data operations and NoSQL database management.', 'remote', 'data', 119, false, false, true),
('Deepgraph Rust', 'deepgraph-rust', 'Analyze Rust codebases with ownership flow, trait relationships, and module dependency graphs.', 'remote', 'development', 117, false, false, true),
('Stripe Integration', 'stripe-integration', 'MCP server for Stripe payment processing integration.', 'remote', 'automation', 114, false, false, true),
('Resend', 'resend', 'MCP server for Resend email sending service integration.', 'remote', 'communication', 105, false, false, true),
('Deepgraph Go', 'deepgraph-go', 'Analyze Go codebases with package dependency graphs, interface implementations, and goroutine patterns.', 'remote', 'development', 103, false, false, true),
('Audioscribe Lite', 'audioscribe-lite', 'Lightweight audio transcription capabilities for quick audio-to-text conversion.', 'remote', 'ai', 101, false, false, true),
('Mailgun', 'mailgun', 'MCP server for Mailgun email delivery service integration.', 'remote', 'communication', 95, false, false, true),
('MCP Pandoc', 'mcp-pandoc', 'Document format conversion using Pandoc. Convert between Markdown, HTML, PDF, DOCX, and more.', 'remote', 'development', 90, false, false, true),
('Deepgraph Java', 'deepgraph-java', 'Analyze Java codebases with class hierarchies, Spring patterns, and package dependency graphs.', 'remote', 'development', 87, false, false, true),
('Perplexity', 'perplexity', 'AI-powered search and research capabilities via Perplexity API.', 'remote', 'ai', 80, false, false, true),
('Airtable', 'airtable', 'MCP server for Airtable database and collaboration platform integration.', 'remote', 'data', 75, false, false, true),
('Val Town', 'val-town', 'MCP server for Val Town serverless function platform integration.', 'remote', 'automation', 67, false, false, true),
('Deepgraph Swift', 'deepgraph-swift', 'Analyze Swift codebases with protocol conformance, class hierarchies, and module dependency graphs.', 'remote', 'development', 66, false, false, true),
('YouTube Transcript', 'youtube-transcript', 'Extract and process YouTube video transcripts for analysis and summarization.', 'remote', 'ai', 61, false, false, true),
('Loops', 'loops', 'MCP server for Loops email marketing platform integration.', 'remote', 'communication', 55, false, false, true),
('Deepgraph Kotlin', 'deepgraph-kotlin', 'Analyze Kotlin codebases with coroutine flows, class hierarchies, and module dependency analysis.', 'remote', 'development', 50, false, false, true),
('Audioscribe Pro', 'audioscribe-pro', 'Professional audio transcription with advanced features like speaker diarization and multi-language support.', 'remote', 'ai', 43, false, false, true),
('PocketBase CRUD', 'pocketbase-crud', 'CRUD operations for PocketBase collections and records.', 'remote', 'data', 35, false, false, true)
ON CONFLICT (slug) DO UPDATE SET
  usage_count = EXCLUDED.usage_count,
  description = EXCLUDED.description,
  updated_at = now();
